# These are supported funding model platforms

# GitHub Sponsors username
# github: 996Worker

# Custom donation links (up to 4)
custom:
  - https://etherscan.io/address/openjdk.eth

# Crypto donations
# ETH/EVM Address: openjdk.eth
